//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locust {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Locust.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Sonora Software..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;MM/dd/yyyy&apos;.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;MM-dd-yyyy&apos;.
        /// </summary>
        public static string DateFormatWithUnderScore {
            get {
                return ResourceManager.GetString("DateFormatWithUnderScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/img/default-user.png.
        /// </summary>
        public static string DefaultImage {
            get {
                return ResourceManager.GetString("DefaultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the project: {0}.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The type: {0} does not exits..
        /// </summary>
        public static string DownloadType {
            get {
                return ResourceManager.GetString("DownloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The test execution with the ID: {0} does not exits..
        /// </summary>
        public static string ExecutionIdInvalid {
            get {
                return ResourceManager.GetString("ExecutionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The group related with the test execution: {0} is not automated..
        /// </summary>
        public static string IsNotAutomated {
            get {
                return ResourceManager.GetString("IsNotAutomated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries to show.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /^(?:(?:https?|ftp):\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,}))\.?)(?::\d{2,5})?(?:[/?#]\S*)?$/i.
        /// </summary>
        public static string RegexURL {
            get {
                return ResourceManager.GetString("RegexURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runner with the identifier: {0} has been deleted..
        /// </summary>
        public static string RunnerDeleted {
            get {
                return ResourceManager.GetString("RunnerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The runner with the identifier: {0} does not exists on the database..
        /// </summary>
        public static string RunnerDoesNotExists {
            get {
                return ResourceManager.GetString("RunnerDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The runner with the identifier: {0} exists on the database..
        /// </summary>
        public static string RunnerExists {
            get {
                return ResourceManager.GetString("RunnerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The runner with the identifier: {0} does not exits..
        /// </summary>
        public static string RunnerIdentifierInvalid {
            get {
                return ResourceManager.GetString("RunnerIdentifierInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The runner with the identifier: {0} is not activated..
        /// </summary>
        public static string RunnerNotActivated {
            get {
                return ResourceManager.GetString("RunnerNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last connection date related to the runner with identifier: {0} has been updated/.
        /// </summary>
        public static string RunnerUpdated {
            get {
                return ResourceManager.GetString("RunnerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The token provided is not valid..
        /// </summary>
        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPECHI.
        /// </summary>
        public static string VersionName {
            get {
                return ResourceManager.GetString("VersionName", resourceCulture);
            }
        }
    }
}
