// <auto-generated />
namespace Locus.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sizeimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sizeimage));
        
        string IMigrationMetadata.Id
        {
            get { return "201901181541206_size-image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
