// <auto-generated />
namespace Locus.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class runner_version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(runner_version));
        
        string IMigrationMetadata.Id
        {
            get { return "201911251724250_runner_version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
